name: puzzlechat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image: ^2.1.11
  argon_buttons_flutter: ^1.0.2
  image_gallery_saver: ^1.2.2
  firebase_auth: ^0.16.0
  equatable: ^1.1.1
  flutter_bloc: ^3.0.0
  dotted_border: ^1.0.5
  animated_widgets: ^1.0.4
  image_picker:
  like_button: ^0.2.0
  contacts_service: ^0.4.6
  permission_handler: ^5.0.0+hotfix.5
  flutter_country_picker: ^0.1.6
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  uuid: ^2.0.4
  http: ^0.12.1
  path_provider: ^1.6.8




dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
     - family: Great Vibes
       fonts:
         - asset: fonts/GreatVibes-Regular.ttf


